In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"   #(xxxx is your specific GPU ID)

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
import numpy as np
import scipy.stats as st

# Group model

In [4]:
Perfomance = pd.read_csv('Performance_0608_training_Data_Size.csv')
Perfomance

,Model,Size,Time,Partcp_Acc_p15,Command_Acc_p15,Partcp_Acc_p1,Command_Acc_p1,Partcp_Acc_p2,Command_Acc_p2,Partcp_Acc_p3,Command_Acc_p3,Partcp_Acc_p4,Command_Acc_p4,Partcp_Acc_p5,Command_Acc_p5,Acc_p6,Acc_p7,Acc_p8
0,Group,10,47.540156,0.9724,0.9484,0.991,0.9550,0.9259,0.8796,0.9652,0.9565,0.9817,0.9633,1.00,0.99,0.67,0.528,0.3366
1,Group,10,48.307249,0.9779,0.9521,1.000,0.9369,0.9352,0.8796,0.9739,0.9652,0.9908,0.9908,0.99,0.99,0.59,0.528,0.2970
2,Group,10,46.201615,0.9613,0.9448,0.991,0.9369,0.9074,0.8611,0.9826,0.9652,0.9358,0.9725,0.99,0.99,0.67,0.432,0.2673
3,Group,10,43.692362,0.9650,0.9521,1.000,0.9459,0.9074,0.8704,0.9826,0.9652,0.9358,0.9908,1.00,0.99,0.62,0.504,0.2673
4,Group,10,44.504580,0.9687,0.9484,0.991,0.9550,0.9259,0.8796,0.9739,0.9652,0.9541,0.9541,1.00,0.99,0.59,0.472,0.3267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Group,20&s2_30,65.672576,0.9908,0.9834,0.973,0.9820,1.0000,0.9537,0.9913,0.9913,0.9908,0.9908,1.00,1.00,0.68,0.424,0.2970
86,Group,20&s2_30,62.740435,0.9926,0.9816,0.982,0.9640,1.0000,0.9722,0.9913,0.9913,0.9908,0.9817,1.00,1.00,0.66,0.424,0.3168
87,Group,20&s2_30,60.706642,0.9945,0.9779,0.991,0.9730,1.0000,0.9444,1.0000,0.9913,0.9817,0.9817,1.00,1.00,0.61,0.464,0.3069
88,Group,20&s2_30,60.410302,0.9926,0.9816,0.982,0.9820,1.0000,0.9444,0.9913,0.9913,0.9908,0.9908,1.00,1.00,0.68,0.480,0.3267
89,Group,20&s2_30,56.029758,0.9945,0.9761,0.991,0.9820,1.0000,0.9259,0.9913,0.9913,0.9908,0.9817,1.00,1.00,0.73,0.440,0.2772

In [5]:
Perfomance.columns

Index(['Model', 'Size', 'Time', 'Partcp_Acc_p15', 'Command_Acc_p15',
       'Partcp_Acc_p1', 'Command_Acc_p1', 'Partcp_Acc_p2', 'Command_Acc_p2',
       'Partcp_Acc_p3', 'Command_Acc_p3', 'Partcp_Acc_p4', 'Command_Acc_p4',
       'Partcp_Acc_p5', 'Command_Acc_p5', 'Acc_p6', 'Acc_p7', 'Acc_p8'],
      dtype='object')

In [6]:
Command_performance = Perfomance[['Model', 'Size', 'Time','Command_Acc_p15','Command_Acc_p1', 'Command_Acc_p2',
                                  'Command_Acc_p3', 'Command_Acc_p4', 'Command_Acc_p5', 'Acc_p6', 'Acc_p7', 'Acc_p8']]
Partcp_performance = Perfomance[['Model', 'Size', 'Time','Partcp_Acc_p15', 'Partcp_Acc_p1', 'Partcp_Acc_p2', 
                                  'Partcp_Acc_p3','Partcp_Acc_p4', 'Partcp_Acc_p5']]

In [7]:
Command_performance

,Model,Size,Time,Command_Acc_p15,Command_Acc_p1,Command_Acc_p2,Command_Acc_p3,Command_Acc_p4,Command_Acc_p5,Acc_p6,Acc_p7,Acc_p8
0,Group,10,47.540156,0.9484,0.9550,0.8796,0.9565,0.9633,0.99,0.67,0.528,0.3366
1,Group,10,48.307249,0.9521,0.9369,0.8796,0.9652,0.9908,0.99,0.59,0.528,0.2970
2,Group,10,46.201615,0.9448,0.9369,0.8611,0.9652,0.9725,0.99,0.67,0.432,0.2673
3,Group,10,43.692362,0.9521,0.9459,0.8704,0.9652,0.9908,0.99,0.62,0.504,0.2673
4,Group,10,44.504580,0.9484,0.9550,0.8796,0.9652,0.9541,0.99,0.59,0.472,0.3267
...,...,...,...,...,...,...,...,...,...,...,...,...
85,Group,20&s2_30,65.672576,0.9834,0.9820,0.9537,0.9913,0.9908,1.00,0.68,0.424,0.2970
86,Group,20&s2_30,62.740435,0.9816,0.9640,0.9722,0.9913,0.9817,1.00,0.66,0.424,0.3168
87,Group,20&s2_30,60.706642,0.9779,0.9730,0.9444,0.9913,0.9817,1.00,0.61,0.464,0.3069
88,Group,20&s2_30,60.410302,0.9816,0.9820,0.9444,0.9913,0.9908,1.00,0.68,0.480,0.3267
89,Group,20&s2_30,56.029758,0.9761,0.9820,0.9259,0.9913,0.9817,1.00,0.73,0.440,0.2772

In [8]:
Partcp_performance[['Model','Size','Time','Partcp_Acc_p15','Partcp_Acc_p1', 'Partcp_Acc_p2',
                                  'Partcp_Acc_p3', 'Partcp_Acc_p4', 'Partcp_Acc_p5']].groupby('Size').mean()

,Time,Partcp_Acc_p15,Partcp_Acc_p1,Partcp_Acc_p2,Partcp_Acc_p3,Partcp_Acc_p4,Partcp_Acc_p5
Size,,,,,,,
10,45.011133,0.96907,0.9946,0.91759,0.97738,0.95963,0.997
10&s12_20,50.566577,0.97752,0.9964,0.98886,0.96868,0.94129,0.994
10&s1_20&s2_30,52.946382,0.97753,0.9928,1.00000,0.96085,0.94495,0.991
10&s2_20,45.593886,0.98195,0.9910,0.99259,0.96781,0.96513,0.995
10&s2_30,49.072065,0.98472,0.9937,1.00000,0.97999,0.96057,0.990
20,57.061598,0.99154,0.9910,0.98795,0.99217,0.98715,1.000
20&s2_30,63.185908,0.99263,0.9847,0.99907,0.99391,0.98624,1.000
30,74.408518,0.99301,0.9829,0.99444,0.99739,0.99080,1.000
6,36.218071,0.95266,0.9865,0.89814,0.96085,0.92569,0.994

In [9]:
Command_performance[['Model','Size','Time','Command_Acc_p15','Command_Acc_p1', 'Command_Acc_p2',
                                  'Command_Acc_p3', 'Command_Acc_p4', 'Command_Acc_p5', 'Acc_p6', 'Acc_p7', 'Acc_p8']].groupby('Size').mean()

,Time,Command_Acc_p15,Command_Acc_p1,Command_Acc_p2,Command_Acc_p3,Command_Acc_p4,Command_Acc_p5,Acc_p6,Acc_p7,Acc_p8
Size,,,,,,,,,,
10,45.011133,0.95157,0.94684,0.87869,0.96607,0.97706,0.991,0.636,0.4944,0.30591
10&s12_20,50.566577,0.96687,0.97300,0.93886,0.95911,0.97710,0.988,0.655,0.4816,0.29997
10&s1_20&s2_30,52.946382,0.97054,0.97030,0.96111,0.95737,0.97710,0.989,0.667,0.4584,0.29700
10&s2_20,45.593886,0.96317,0.94685,0.93611,0.96607,0.98077,0.988,0.699,0.5112,0.28611
10&s2_30,49.072065,0.96208,0.93240,0.95834,0.95824,0.97985,0.984,0.676,0.5128,0.30591
20,57.061598,0.97477,0.97030,0.92779,0.98869,0.98898,0.999,0.695,0.4504,0.28017
20&s2_30,63.185908,0.98067,0.97300,0.95370,0.98956,0.98807,1.000,0.687,0.4560,0.29304
30,74.408518,0.98434,0.98560,0.95832,0.98956,0.98898,1.000,0.694,0.4288,0.26235
6,36.218071,0.92062,0.93510,0.82130,0.94084,0.94129,0.966,0.528,0.4456,0.30987

# calculate by build in function

In [10]:
confidence = pd.DataFrame(columns=["Size", 'Time-low','Time-high', 'Keyword-low', 'Keyword-high','Speaker-low','Speaker-high'])
confidence['Size'] = Perfomance['Size'].unique() 
for size in Perfomance['Size'].unique():
    confidence.loc[confidence['Size'] == size,['Time-low','Time-high']] =  st.t.interval(alpha=0.95, df=len(Perfomance.loc[Perfomance['Size'] == size,'Time']), loc=np.mean(Perfomance.loc[Perfomance['Size'] == size,'Time']), scale=st.sem(Perfomance.loc[Perfomance['Size'] == size,'Time'])) 
    confidence.loc[confidence['Size'] == size,['Keyword-low','Keyword-high']] =  st.t.interval(alpha=0.95, df=len(Perfomance.loc[Perfomance['Size'] == size,'Command_Acc_p15']), loc=np.mean(Perfomance.loc[Perfomance['Size'] == size,'Command_Acc_p15']), scale=st.sem(Perfomance.loc[Perfomance['Size'] == size,'Command_Acc_p15'])) 
    confidence.loc[confidence['Size'] == size,['Speaker-low','Speaker-high']] =  st.t.interval(alpha=0.95, df=len(Perfomance.loc[Perfomance['Size'] == size,'Partcp_Acc_p15']), loc=np.mean(Perfomance.loc[Perfomance['Size'] == size,'Partcp_Acc_p15']), scale=st.sem(Perfomance.loc[Perfomance['Size'] == size,'Partcp_Acc_p15'])) 
confidence

,Size,Time-low,Time-high,Keyword-low,Keyword-high,Speaker-low,Speaker-high
0,10,43.6979,46.3243,0.948761,0.954379,0.965512,0.972628
1,30,70.7848,78.0323,0.982017,0.986663,0.99167,0.99435
2,10&s2_20,43.7205,47.4673,0.958876,0.967464,0.978037,0.985863
3,10&s12_20,48.9825,52.1507,0.964511,0.969229,0.973866,0.981174
4,10&s2_30,47.111,51.0331,0.957703,0.966457,0.980261,0.989179
5,10&s1_20&s2_30,50.9882,54.9045,0.96809,0.97299,0.975429,0.979631
6,6,35.025,37.4111,0.914272,0.926968,0.946824,0.958496
7,20,54.1617,59.9615,0.972107,0.977433,0.989687,0.993393
8,20&s2_30,59.8553,66.5165,0.978921,0.982419,0.991409,0.993851

In [11]:
confidence[['Time-low','Time-high', 'Keyword-low', 'Keyword-high','Speaker-low','Speaker-high']] = confidence[['Time-low','Time-high', 'Keyword-low', 'Keyword-high','Speaker-low','Speaker-high']].astype('float')

In [12]:
confidence.round(3)

,Size,Time-low,Time-high,Keyword-low,Keyword-high,Speaker-low,Speaker-high
0,10,43.698,46.324,0.949,0.954,0.966,0.973
1,30,70.785,78.032,0.982,0.987,0.992,0.994
2,10&s2_20,43.721,47.467,0.959,0.967,0.978,0.986
3,10&s12_20,48.982,52.151,0.965,0.969,0.974,0.981
4,10&s2_30,47.111,51.033,0.958,0.966,0.980,0.989
5,10&s1_20&s2_30,50.988,54.905,0.968,0.973,0.975,0.980
6,6,35.025,37.411,0.914,0.927,0.947,0.958
7,20,54.162,59.962,0.972,0.977,0.990,0.993
8,20&s2_30,59.855,66.517,0.979,0.982,0.991,0.994

# calculate by hand

In [13]:
confidence = pd.DataFrame(columns=["Size", 'Time_mean','Time+_', 'Keyword_mean', 'Keyword+_','Speaker_mean','Speaker+_'])
confidence['Size'] = Perfomance['Size'].unique()

In [14]:
t_value = 2.262 # df=9, alpha = 0.05, two tails
def CI_95(data):
    n=len(data)
    x_bar = data.mean()
    x_std = data.std()
    CI = t_value*x_std/np.sqrt(n)
    return x_bar, CI

In [15]:
for size in Perfomance['Size'].unique():
    confidence.loc[confidence['Size'] == size,['Time_mean','Time+_']] = CI_95(Perfomance.loc[Perfomance['Size'] == size,'Time']) 
    confidence.loc[confidence['Size'] == size,['Keyword_mean', 'Keyword+_']] = CI_95(Perfomance.loc[Perfomance['Size'] == size,'Command_Acc_p15']) 
    confidence.loc[confidence['Size'] == size,['Speaker_mean','Speaker+_']] = CI_95(Perfomance.loc[Perfomance['Size'] == size,'Partcp_Acc_p15'])  
confidence

,Size,Time_mean,Time+_,Keyword_mean,Keyword+_,Speaker_mean,Speaker+_
0,10,45.0111,1.33314,0.95157,0.00285208,0.96907,0.00361229
1,30,74.4085,3.67881,0.98434,0.00235827,0.99301,0.00136074
2,10&s2_20,45.5939,1.90185,0.96317,0.00435954,0.98195,0.00397255
3,10&s12_20,50.5666,1.60819,0.96687,0.00239436,0.97752,0.00370947
4,10&s2_30,49.0721,1.99083,0.96208,0.00444346,0.98472,0.00452686
5,10&s1_20&s2_30,52.9464,1.9879,0.97054,0.00248687,0.97753,0.00213318
6,6,36.2181,1.21118,0.92062,0.00644454,0.95266,0.00592485
7,20,57.0616,2.94401,0.97477,0.00270371,0.99154,0.00188114
8,20&s2_30,63.1859,3.38123,0.98067,0.00177568,0.99263,0.00123943

In [16]:
confidence[['Time_mean','Time+_', 'Keyword_mean', 'Keyword+_','Speaker_mean','Speaker+_']] = confidence[['Time_mean','Time+_', 'Keyword_mean', 'Keyword+_','Speaker_mean','Speaker+_']].astype('float')

In [17]:
confidence.round(4)

,Size,Time_mean,Time+_,Keyword_mean,Keyword+_,Speaker_mean,Speaker+_
0,10,45.0111,1.3331,0.9516,0.0029,0.9691,0.0036
1,30,74.4085,3.6788,0.9843,0.0024,0.9930,0.0014
2,10&s2_20,45.5939,1.9019,0.9632,0.0044,0.9820,0.0040
3,10&s12_20,50.5666,1.6082,0.9669,0.0024,0.9775,0.0037
4,10&s2_30,49.0721,1.9908,0.9621,0.0044,0.9847,0.0045
5,10&s1_20&s2_30,52.9464,1.9879,0.9705,0.0025,0.9775,0.0021
6,6,36.2181,1.2112,0.9206,0.0064,0.9527,0.0059
7,20,57.0616,2.9440,0.9748,0.0027,0.9915,0.0019
8,20&s2_30,63.1859,3.3812,0.9807,0.0018,0.9926,0.0012